model:
  model_name: microsoft/deberta-v3-small
  name: "glinext"
  max_width: 12
  hidden_size: 768
  dropout: 0.3
  fine_tune: true
  subtoken_pooling: first
  span_mode: markerV0
  max_types: 100
  max_len: 512
  max_neg_type_ratio: 1

  ner_config:
    scorer_type: "gliner"
    loss_coef: 1.0
    focal_loss_alpha: null
    focal_loss_gamma: null
    focal_loss_prob_margin: null
    represent_spans: false

  classification_config:
    layer_type: "dot"
    pooling_type: "mean"
    loss_coef: 1.0
    focal_loss_alpha: null
    focal_loss_gamma: null
    focal_loss_prob_margin: null

  structuring_config:
    anchor_layer:
      type: "rotary"
      params:
        max_count: 20
    anchor_normalization: "none"
    anchor_modeling: "linear"
    anchor_refinement: "none"
    max_count: 20
    loss_coef: 1.0
    focal_loss_alpha: null
    focal_loss_gamma: null
    focal_loss_prob_margin: null
    represent_spans: false
    use_anchor_matching: true
    bio_loss_reduction: "mean"
    anchor_objectness: false

  joint_relex_config: null
  open_relex_config: null
  count_config: null
  embedding_config: null

data:
  root_dir: logs/ner_classification_structuring
  train_data: "data/bio_post_ner_gliclass_logic_structuring.jsonl"
  val_data: "none"

training:
  prev_path: null
  num_steps: 200000
  train_batch_size: 1
  gradient_accumulation_steps: 8
  eval_every: 10000
  warmup_ratio: 0.05
  scheduler_type: "cosine"
  focal_loss_alpha: 0.75
  focal_loss_gamma: 0
  loss_reduction: "sum"
  lr_encoder: 2e-5
  lr_others: 3e-5
  weight_decay_encoder: 0.01
  weight_decay_other: 0.01
  max_grad_norm: 10.0
  save_total_limit: 3
  train_head_only: false
  bf16: true
